In [2]:
import pandas as pd
import numpy as np

In [ ]:
#открылось что-то странное
df = pd.read_csv ('https://raw.githubusercontent.com/mathling-programming/practice2022/main/exercise2m/sample.csv',  sep= '\t')
df

# Sample data
0     5.562520486164440854e+02,3.687894902108730548e...
1     8.256913538581953844e+02,2.071550210545871664e...
2     2.250452273573475566e+02,8.999226141145671818e...
3     7.616185037813037297e+02,9.614756936859930647e...
4     4.524781044052792254e+02,4.526231065117344201e...
...                                                 ...
9995  1.651652874916282769e+02,3.623436105958754752e...
9996  9.758836313027243250e+02,7.246644617938175088e...
9997  1.663857361789752360e+02,6.349943089847001829e...
9998  2.215412548584055799e+02,1.933287572594707342e...
9999  7.310211435090312762e+02,8.290525924496167818e...

[10000 rows x 1 columns]

In [16]:
#второй вариант
df = np.genfromtxt('https://raw.githubusercontent.com/mathling-programming/practice2022/main/exercise2m/sample.csv', delimiter=',', skip_header=1)
#возвращает массив, считанный из файла
df

array([[556.25204862, 368.78949021, 354.06059711, ..., 340.03413915,
        759.33936397, 595.54906505],
       [825.69135386, 207.15502105, 113.48800391, ..., 808.06037246,
         49.07588663,  24.67801906],
       [225.04522736, 899.92261411, 672.08736477, ..., 280.67671352,
        414.8141431 , 550.56728211],
       ...,
       [166.38573618, 634.99430898, 554.97806091, ..., 187.2714981 ,
        312.01718305, 176.58642322],
       [221.54125486, 193.32875726, 970.16990676, ...,  75.80406886,
        653.58118857, 630.44493794],
       [731.02114351, 829.05259245, 766.32542181, ..., 803.11236784,
        708.44619508, 524.64086715]])

In [17]:
num = 0 #нумерация строк
result = np.empty(shape=[0, 3]) #пустая матрица для записи результатов
#https://stackoverflow.com/questions/568962/how-do-i-create-an-empty-array-and-then-append-to-it-in-numpy

for i in df[:,]: #все строчки в массиве
  num += 1 #считаем строчки в массиве
  mean = np.mean(i) #арифметическое среднее
  std = np.std(i) #среднеквадратичное отклонение

  if std < 250: #строки со среднеквадратичным отклонением меньше 250
    result = np.append(result, np.array([[num, mean, std]]), axis=0) #пополняем номером строки, средним, среднеквадратичным; обозначаем ось

print(result)  

[[ 130.          496.80431767  249.39333383]
 [1380.          468.63313644  246.86983032]
 [1542.          518.9311636   241.28790697]
 [1839.          506.03440045  244.47839358]
 [2917.          456.47080409  244.59411095]
 [3411.          514.375227    243.18450599]
 [3556.          571.4821826   249.29582101]
 [3604.          466.08394861  247.2685776 ]
 [3823.          503.57595506  238.76853318]
 [4102.          481.92328233  238.07662388]
 [4149.          485.07220222  248.85098666]
 [4285.          447.41639528  248.59076459]
 [4351.          461.4737511   247.28303079]
 [4558.          472.25844117  247.33420758]
 [4861.          497.50829821  241.45579774]
 [5106.          551.67423034  245.97923256]
 [5693.          523.17584725  243.33756   ]
 [6292.          538.23833912  240.58904694]
 [6525.          506.40614679  246.04283179]
 [7140.          551.41421905  245.06458916]
 [8097.          504.22961766  248.61282065]
 [8303.          437.78740512  232.64042596]
 [8688.   

In [18]:
#fmt= %[flag]width[.precision]specifier
#precision -- количество цифр после запятой для записи вещественных чисел (например, e, E, f);
#https://pyprog.pro/io_functions/savetxt.html?ysclid=lfuxrt4mid36138291 

np.savetxt('output.txt', result, fmt='%.2f', delimiter='\t')

#некрасиво, что номер строки тоже указывается с цифрами после запятой, но я не нашла как убрать только для одного столбца