In [1]:
import numpy as np

In [2]:
file = np.genfromtxt('sample.csv', delimiter=',', skip_header=1)
file

array([[556.25204862, 368.78949021, 354.06059711, ..., 340.03413915,
        759.33936397, 595.54906505],
       [825.69135386, 207.15502105, 113.48800391, ..., 808.06037246,
         49.07588663,  24.67801906],
       [225.04522736, 899.92261411, 672.08736477, ..., 280.67671352,
        414.8141431 , 550.56728211],
       ...,
       [166.38573618, 634.99430898, 554.97806091, ..., 187.2714981 ,
        312.01718305, 176.58642322],
       [221.54125486, 193.32875726, 970.16990676, ...,  75.80406886,
        653.58118857, 630.44493794],
       [731.02114351, 829.05259245, 766.32542181, ..., 803.11236784,
        708.44619508, 524.64086715]])

In [3]:
a1 = np.mean(file, axis=1)
a1

array([549.90549026, 454.55478538, 491.39573877, ..., 515.53768957,
       538.22819532, 498.67233238])

In [4]:
a2 = np.std(file, axis=1)
a2

array([271.19701109, 311.47028202, 281.83971392, ..., 288.40530063,
       279.70263441, 296.63114126])

In [5]:
a3 = np.array(range(1, len(file) + 1))

In [6]:
a4 = np.vstack([a3, a1, a2]).T
a4

array([[1.00000000e+00, 5.49905490e+02, 2.71197011e+02],
       [2.00000000e+00, 4.54554785e+02, 3.11470282e+02],
       [3.00000000e+00, 4.91395739e+02, 2.81839714e+02],
       ...,
       [9.99800000e+03, 5.15537690e+02, 2.88405301e+02],
       [9.99900000e+03, 5.38228195e+02, 2.79702634e+02],
       [1.00000000e+04, 4.98672332e+02, 2.96631141e+02]])

In [7]:
a = a4[a4[..., 2] < 250]

In [8]:
np.savetxt('output.txt', a, delimiter='\t', fmt='%.2f')